service: ytdl
provider:
  name: aws
  runtime: nodejs12.x
plugins:
  - serverless-plugin-monorepo
  - serverless-dotenv-plugin
functions:
  app:
    handler: dist/src/index.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY
